version: '3.8'

services:

  # database: persistence
  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: home
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: home
      MYSQL_ROOT_PASSWORD: password

  # liquibase: database setup. takes about 1 minute to finish.
  liquibase:
    image: liquibase/liquibase:4.25.0
    environment:
      INSTALL_MYSQL: 'true'
    links:
      - db
    volumes:
      - ../../backend/database:/liquibase/changelog:ro
    command: [
      "--url=jdbc:mysql://db:3306/home?allowPublicKeyRetrieval=true&autoReconnect=true&maxReconnects=20",
      "--changeLogFile=org/ivcode/homeportal/changelog/db.changelog-root.yml",
      "--username=home",
      "--password=password",
      "update"
    ]
  
  home-portal:
    image: home-portal
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/home?allowPublicKeyRetrieval=true
      DATABASE_USERNAME: home
      DATABASE_PASSWORD: password
      