version: '3.8'

services:

  # database: persistence
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_USER: home
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: home
      MYSQL_ROOT_PASSWORD: password
  
  # home-portal
  home-portal:
    image: home-portal
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/home?allowPublicKeyRetrieval=true&autoReconnect=true&maxReconnects=20
      DATABASE_USERNAME: home
      DATABASE_PASSWORD: password
