version: '3.8'

services:

  # database: persistence
  db:
    image: "mysql:8.0"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_USER: home
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: home
      MYSQL_ROOT_PASSWORD: password
  
  # home-portal
  home-portal:
    image: home-portal:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/home?allowPublicKeyRetrieval=true
      DATABASE_USERNAME: home
      DATABASE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
