spring:
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/home?allowPublicKeyRetrieval=true
    username: home
    password: password


springdoc:
  api-docs:
    resolve-schema-properties: true
  writer-with-order-by-keys: true

logging:
  level:
    org.springframework: WARN
    org.ivcode: DEBUG
  file: logs/spring-boot-logging.log