version: '3.8'

services:
  # nginx: reverse proxy
  nginx:
    image: "nginx:latest"
    ports:
      - 80:80
    volumes:
     - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  # database: persistence
  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    volumes:
     - "./initdb:/docker-entrypoint-initdb.d:ro"
    environment:
      MYSQL_USER: home
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: home
      MYSQL_ROOT_PASSWORD: password

  # liquibase: database setup. takes about 1 minute to finish.
  liquibase:
   image: liquibase/liquibase:4.25.0
   environment:
     INSTALL_MYSQL: 'true'
   links:
     - db
   volumes:
     - ../../database:/liquibase/changelog:ro
   command: [
     "--url=jdbc:mysql://db:3306/home?allowPublicKeyRetrieval=true&autoReconnect=true&maxReconnects=20",
     "--changeLogFile=db.changelog-root.yml",
     "--username=home",
     "--password=password",
     "update"
   ]
  
  # keycloak: OAuth2
  keycloak:
    image: "quay.io/keycloak/keycloak:23.0.3"
    restart: always
    ports:
      - 8081:8080
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_PROPERTIES: ?connectTimeout=60&allowPublicKeyRetrieval=true&autoReconnect=true&maxReconnects=20
      KC_PROXY: edge
    command: [
      "start-dev",
      "--http-relative-path",
      "/auth"
    ]
